:default ::= action => [values] bless => ::lhs
lexeme default = action => [start,length,value] bless => ::name
:start ::= PotentiallySystematizedDocument
s ~ RE
  | RS
  | SPACE
  | SEPCHAR
sStar ~ s*
sPlus ~ s+
ps ~ s
   | Ee
   | ParameterEntityReference
   | CommentDeclaration
psStar ~ ps*
psPLus ~ ps+
ts ~ s
   | Ee
   | ParameterEntityReference
tsStar ~ ts*
tsPLus ~ ts+
ds ~ s
   | Ee
   | ParameterEntityReference
   | CommentDeclaration
   | ProcessingInstruction
   | MarkedSectionDeclaration
dsStar ~ ds*
dsPLus ~ ds+
PotentiallySystematizedDocument ~ OpeningSystemDeclarationList SGMLDocument bless => TOP
OpeningSystemDeclarationList ~ OpeningSystemDeclaration*
OpeningSystemDeclaration ~ SystemDeclaration sPlus
SGMLDocument ~ SGMLDocumentEntity SGMLDocumentGutsStar bless => DOCUMENT
SGMLDocumentGutsStar ~ SGMLDocumentGuts*
SGMLDocumentGuts ~ SGMLSubDocumentEntity
                 | SGMLTextEntity
                 | CharacterDataEntity
                 | SpecificCharacterDataEntity
                 | NonSGMLData
SGMLDocumentEntity ~ sStar SGMLDeclaration Prolog DocumentInstanceSet Ee
SGMLSubDocumentEntity ~ Prolog DocumentInstanceSet Ee
SGMLTextEntity ~ SGMLCharacterStar Ee bless => TEXT
CharacterDataEntity ~ SGMLCharacterStar Ee bless => CDATA
SpecificCharacterDataEntity ~ SGMLCharacterStar Ee bless => CDATA
NonSGMLData ~ CharacterStar Ee bless => CRUFT
Prolog ~ OtherPrologStar DTD DTDOP LTDOP bless => PROLOG
DTDOP ~ DTDOP*
DTDOPAtom ~ DTD
          | OtherProlog
LTDOP ~ LTDOPAtom*
LTDOPAtom ~ LTD
          | OtherProlog
OtherPrologStar ~ OtherProlog*
OtherProlog ~ CommentDeclaration
            | ProcessingInstruction
            | s
DocumentInstanceSet ~ BaseDocumentElement OtherProlog*
BaseDocumentElement ~ DocumentElement
DocumentElement ~ Element
Element ~ StartTag Content EndTag bless => ELEMENT
        |          Content EndTag bless => ELEMENT
        | StartTag Content        bless => ELEMENT
        |          Content        bless => ELEMENT
StartTag ~ stago TagType AttributeSpecificationPlus sStar tagc bless => TAG @closed => 1 @type => start assoc => group
         | MinimizedStartTag bless => TAG @type => start
MinimizedStartTag ~ EmptyStartTag
                  | UnclosedStartTag
                  | NetEnablingStartTag
EmptyStartTag ~ stago tagc @closed => 1
UnclosedStartTag ~ stago TagType AttributeSpecificationPlus sStar @closed => 0
NetEnablingStartTag ~ stago NetTagType AttributeSpecificationPlus sStar neto @closed => 1 @matching => $1
EndTag ~ etago TagType sStar tagc bless => TAG @closed => 1 @type => end assoc => group
       | MinimizedEndTag bless => TAG @type => end
MinimizedEndTag ~ EmptyEndTag
                | UnclosedEndTag
                | NullEndTag
EmptyEndTag ~ etago tagc @closed => 1
UnclosedEndTag ~ etago TagType sStar @closed => 0
NullEndTag ~ netc @closed => 1
TagType ~ DocumentTypeSpecification GenericIdentifierSpecification
NetTagType ~ GenericIdentifierSpecification bless => TagType
ContentPlus ~ Content+
ContentStar ~ Content*
Content ~ MixedContentStar
        | ElementContentStar
        | ReplaceableCharacterDataStar
        | CharacterData bless => CDATA
MixedContentStar ~ MixedContentStar
MixedContent ~ DataCharacter bless => PCDATA
             | Element bless => PCDATA
             | OtherContent bless => PCDATA
ElementContentStar ~ ElementContent*
ElementContent ~ Element
               | OtherContent
               | s
OtherContent ~ CommentDeclaration
             | ShortReferenceUseDeclaration
             | LinkSetUseDeclaration
             | ProcessingInstruction
             | shortref
             | CharacterReference
             | GeneralEntityReference
             | MarkedSectionDeclaration
             | Ee
DocumentTypeSpecification ~ NameGroup
                          | Nothing
GenericIdentifierSpecification ~ GenericIdentifier
                               | RankStem
GenericIdentifier ~ Name
AttributeSpecificationPlus ~ AttributeSpecification+
AttributeSpecification ~ sStar Name sStar vi sStar AttributeValueSpecification bless => ATTRIBUTE
                       | sStar AttributeValueSpecification bless => ATTRIBUTE
AttributeValueSpecification ~ AttributeValue bless => ATTRVAL
                            | AttributeValueLiteral bless => ATTRVAL
AttributeValueLiteral ~ lit ReplaceableCharacterDataStar lit @literal => 1 @quoted => 1 assoc => group
                      | lita ReplaceableCharacterDataStar lita @literal => 1 @quoted => 1 assoc => group
AttributeValue ~ CharacterData
               | GeneralEntityName
               | GeneralEntityNameList
               | IDValue
               | IDReferenceValue
               | IDReferenceList
               | Name
               | NameList
               | NameToken
               | NameTokenList
               | NotationName
               | Number
               | NumberList
               | NumberToken
               | NumberTokenList
GeneralEntityNameList ~ NameList
IDValue ~ Name
IDReferenceList ~ NameList
IDReferenceValue ~ Name
NameList ~ Name
         | Name SPACE NameList
NotationName ~ Name
NumberList ~ Number
           | Number SPACE NumberList
NumberTokenList ~ NumberToken
                | NumberToken SPACE NumberTokenList
ProcessingInstruction ~ pio SystemDataStar pic bless => PI
SystemDataStar ~ SystemData*
SystemData ~ CharacterData
ReplaceableCharacterDataStar ~ ReplaceableCharacterData*
ReplaceableCharacterData ~ DataCharacter bless => RCDATA
                         | CharacterReference bless => RCDATA
                         | GeneralEntityReference bless => RCDATA
                         | Ee bless => RCDATA
CharacterData ~ DataCharacterPlus bless => CDATA
DataCharacterPlus ~ DataCharacter+
DataCharacter ~ SGMLCharacter
CharacterStar ~ Character*
Character ~ SGMLCharacter
          | NONSGML bless => CRUFT
SGMLCharacterStar ~ SGMLCharacter*
SGMLCharacter ~ MarkupCharacter
              | DATACHAR
MarkupCharacter ~ NameCharacter
                | FunctionCharacter
                | DELMCHAR
NameCharacter ~ NameCharacter NameCharacter
              | NameStartCharacter
              | Digit
              | LCNMCHAR
              | UCNMCHAR
NameStartCharacter ~ LCLetter
                   | UCLetter
                   | LCNMSTRT
                   | UCNMSTRT
FunctionCharacter ~ RE
                  | RS
                  | SPACE
                  | SEPCHAR
                  | MSOCHAR
                  | MSICHAR
                  | MSSCHAR
                  | FUNCHAR
Name ~ NameStartCharacter NameCharacter bless => NAME
Number ~ Digit+ bless => NUMBER
NameToken ~ NameCharacter bless => TOKEN
NumberToken ~ Digit NameCharacter bless => TOKEN
GeneralEntityReference ~ ero DocumentTypeSpecification Name ReferenceEnd bless => REF assoc => group @closed => 1
ParameterEntityReference ~ pero DocumentTypeSpecification Name ReferenceEnd bless => REF assoc => group @closed => 1
ReferenceEnd ~ refc
             | refc RE
CharacterReference ~ cro FunctionName ReferenceEnd bless => CREF @numeric => 0 assoc => group @closed => 1
                   | cro CharacterNumber ReferenceEnd bless => CREF @numeric => 1 assoc => group @closed => 1
FunctionName ~ 'RE'
             | 'RS'
             | 'SPACE'
             | Name
CharacterNumber ~ Number
ParameterLiteral ~ lit ReplaceableParameterDataStar lit @literal => 1 @quoted => 1 assoc => group
                 | lita ReplaceableParameterDataStar lita @literal => 1 @quoted => 1 assoc => group
ReplaceableParameterDataStar ~ ReplaceableParameterData*
ReplaceableParameterData ~ DataCharacter
                         | CharacterReference
                         | ParameterEntityReference
                         | Ee
NameTokenGroup ~ grpo tsStar NameToken NameTokenGroupGutsStar tsStar grpc assoc => group @closed => 1
NameTokenGroupGutsStar ~ NameTokenGroupGuts*
NameTokenGroupGuts ~ tsStar Connector NameToken
NameGroup ~ grpo tsStar Name NameGroupGutsStar tsStar grpc
NameGroupGuts ~ tsStar Connector Name
AssociatedElementType ~ GenericIdentifier
                      | NameGroup
ExternalIdentifier ~ 'SYSTEM'
                   | 'PUBLIC' psPlus PublicIdentifier
                   | 'SYSTEM' psPlus SystemIdentifier
                   | 'PUBLIC' psPlus PublicIdentifier psPlus SystemIdentifier
PublicIdentifier ~ MinimumLiteral
SystemIdentifier ~ lit SystemDataStar lit @literal => 1 @quoted => 1 assoc => group
                 | lita SystemDataStar lita @literal => 1 @quoted => 1 assoc => group
MinimumLiteral ~ lit MinimumData lit @literal => 1 @quoted => 1 assoc => group
               | lita MinimumData lita @literal => 1 @quoted => 1 assoc => group
MinimumData ~ MinimumDataCharacter+
MinimumDataCharacter ~ RS
                     | RE
                     | SPACE
                     | LCLetter
                     | UCLetter
                     | Digit
                     | Special
FormalPublicIdentifier ~ OwnerIdentifier slashslash TextIdentifier
OwnerIdentifier ~ ISOOwnerIdentifier
                | RegisteredOwnerIdentifier
                | UnregisteredOwnerIdentifier
ISOOwnerIdentifier ~ MinimumData
RegisteredOwnerIdentifier ~ plus slashslash MinimumData
UnregisteredOwnerIdentifier ~ minus slashslash MinimumData
TextIdentifier ~ PublicTextClass SPACE UnavailableTextIndicator PublicTextGuts slashslash PublicTextLanguage PDTV
               | PublicTextClass SPACE PublicTextGuts slashslash PublicTextLanguage PDTV
               | PublicTextClass SPACE UnavailableTextIndicator PublicTextGuts slashslash PublicTextLanguage
               | PublicTextClass SPACE PublicTextGuts slashslash PublicTextLanguage
PublicTextGuts ~ PublicTextDescription
               | PublicTextDesignatingSequence
PDTV ~ slashslash PublicTextDisplayVersion
UnavailableTextIndicator ~ minus slashslash
PublicTextClass ~ Name
PublicTextDescription ~ ISOTextDescription
                      | MinimumData
ISOTextDescription ~ MinimumData
PublicTextLanguage ~ Name
PublicTextDesignatingSequence ~ Name
CommentDeclaration ~ mdo CommentList mdc bless => COMMENT assoc => group
                   | mdo mdc bless => COMMENT assoc => group
CommentList ~ Comment s
            | Comment s CommentList
Comment ~ com SGMLCharacter* com assoc => group
MarkedSectionDeclaration ~ MarkedSectionStart StatusKeywordSpecification dso MarkedSection MarkedSectionEnd bless => DECL assoc => group @closed => 1
MarkedSectionStart ~ mdo dso
MarkedSectionEnd ~ msc mdc
MarkedSection ~ SGMLCharacter*
StatusKeywordSpecification ~ psPlus StatusKeyword psStar
StatusKeyword ~ 'TEMP'
              | 'CDATA'
              | 'IGNORE'
              | 'INCLUDE'
              | 'RCDATA'
EntityDeclaration ~ mdo 'ENTITY' psPlus EntityName psPlus EntityText psPlus mdc bless => DECL assoc => group @closed => 1
EntityName ~ GeneralEntityName
           | ParameterEntityName
GeneralEntityName ~ Name
                  | rni 'DEFAULT'
ParameterEntityName ~ pero psPlus Name
EntityText ~ ParameterLiteral
           | DataText
           | BracketedText
           | ExternalEntitySpecification
DataText ~ DataTextGuts psPlus ParameterLiteral
DataTextGuts ~ 'CDATA'
             | 'SDATA'
             | 'PI'
BracketedText ~ BracketedTextGuts psPlus ParameterLiteral
BracketedTextGuts ~ 'STARTTAG'
                  | 'ENDTAG'
                  | 'MS'
                  | 'MD'
ExternalEntitySpecification ~ ExternalIdentifier
                            | ExternalIdentifier psPlus EntityType
EntityType ~ 'SUBDOC'
           | 'NDATA' psPlus NotationName DataAttributeSpecification
           | 'CDATA' psPlus NotationName DataAttributeSpecification
           | 'SDATA' psPlus NotationName DataAttributeSpecification
DTD ~ mdo 'DOCTYPE' psPlus DocumentTypeName OptionalEI OptionalWrappedDTDSubset psStar mdc bless => DTD assoc => group @closed => 1
OptionalEI ~ psPlus ExternalIdentifier
           | Nothing
OptionalWrappedDTDSubset ~ WrappedDTDSubset
                         | Nothing
WrappedDTDSubset ~ psPlus WrappedDTDSubsetGuts
WrappedDTDSubsetGuts ~ dso DTDSubsetPlus dsc assoc => group
DocumentTypeName ~ GenericIdentifier
DTDSubsetPlus ~ DTDSubset+
DTDSubset ~ EntitySetPlus
          | ElementSetPlus
          | ShortReferenceSetPlus
EntitySetPlus ~ EntitySet+
EntitySet ~ EntityDeclaration
           | ds
ElementSetPlus ~ ElementSet+
ElementSet ~ ElementDeclaration
           | AttributeDefinitionListDeclaration
           | NotationDeclaration
           | ds
ShortReferenceSetPlus ~ ShortReferenceSet+
ShortReferenceSet ~ EntityDeclaration
                  | ShortReferenceMappingDeclaration
                  | ShortReferenceUseDeclaration
                  | ds
ElementDeclaration ~ mdo 'ELEMENT' psPlus ElementType OptionalOTMGuts psPlus DeclaredContent mdc bless => DECL assoc => group @closed => 1
                   | mdo 'ELEMENT' psPlus ElementType OptionalOTMGuts psPlus ContentModel mdc bless => DECL assoc => group @closed => 1
OptionalOTMGuts ~ OTMGuts
                | Nothing
OTMGuts ~ psPlus OmittedTagMinimization
ElementType ~ GenericIdentifier
            | NameGroup
            | RankedElement
            | RankedGroup
RankedElement ~ RankStem psPlus RankSuffix
RankedGroup ~ grpo tsStar RankStem ConnectedRankStemStar tsStar grpc psPlus RankSuffix
ConnectedRankStemStar ~ ConnectedRankStem*
ConnectedRankStem ~ tsStar Connector tsStar RankStem
RankStem ~ Name
RankSuffix ~ Number
OmittedTagMinimization ~ StartTagMinimization psPlus EndTagMinimization
StartTagMinimization ~ 'O'
                     | '-'
EndTagMinimization ~ 'O'
                   | '-'
DeclaredContent ~ 'CDATA'
                | 'RCDATA'
                | 'EMPTY'
ContentModel ~ ModelGroup OptionalExceptions
             | 'ANY' OptionalExceptions
OptionalExceptions ~ psPlus Exceptions
                   | Nothing
ModelGroup ~ grpo tsStar ContentToken ConnectedContentTokenStar tsStar grpc
ConnectedContentTokenStar ~ ConnectedContentToken*
ConnectedContentToken ~ tsStar Connector tsStar ContentToken
ContentToken ~ PrimitiveContentToken
             | ModelGroup
PrimitiveContentToken ~ rni 'PCDATA'
                      | ElementToken
                      | DataTagGroup
ElementToken ~ GenericIdentifier
             | GenericIdentifier OccurenceIndicator
Connector ~ and
          | or
          | seq
OccurenceIndicator ~ opt
                   | plus
                   | rep
DataTagGroup ~ dtgo tsStar GenericIdentifier tsStar seq tsStar DataTagPattern tsStar dtgc
             | dtgo tsStar GenericIdentifier tsStar seq tsStar DataTagPattern tsStar dtgc OccurenceIndicator
DataTagPattern ~ DataTagTemplate OptionalDataTagPaddingTemplate
               | DataTagTemplateGroup OptionalDataTagPaddingTemplate
OptionalDataTagPaddingTemplate ~ tsStar seq DataTagPaddingTemplate
                               | Nothing
DataTagTemplateGroup ~ grpo tsStar DataTagTemplateList tsStar grpc
DataTagTemplateList ~ DataTagTemplate
                    | DataTagTemplate tsStar or tsStar DataTagTemplateList
DataTagTemplate ~ ParameterLiteral
DataTagPaddingTemplate ~ ParameterLiteral
Exceptions ~ Exclusions
           | Exclusions psPlus Inclusions
           | Inclusions
Inclusions ~ plus NameGroup
Exclusions ~ minus NameGroup
AttributeDefinitionListDeclaration ~ mdo 'ATTLIST' psPlus AssociatedElementType AttributeDefinitionPlus psStar mdc bless => DECL assoc => group
                                   | mdo 'ATTLIST' psPlus AssociatedNotationName AttributeDefinitionPlus psStar mdc bless => DECL assoc => group
AttributeDefinitionPlus ~ AttributeDefinition+
AttributeDefinition ~ psPlus AttributeName psPlus DeclaredValue psPlus DefaultValue
AttributeName ~ Name
DeclaredValue ~ 'CDATA'
              | 'ENTITY'
              | 'ENTITIES'
              | 'ID'
              | 'IDREF'
              | 'IDREFS'
              | 'NAME'
              | 'NAMES'
              | 'NMTOKEN'
              | 'NMTOKENS'
              | 'NUMBER'
              | 'NUMBERS'
              | 'NUTOKEN'
              | 'NUTOKENS'
              | 'NOTATION' psStar NameGroup
              | NameTokenGroup
DefaultValue ~ DVFixedMarker AttributeValueSpecification
             | AttributeValueSpecification
             | rni DVMagicMarker
DVFixedMarker ~ rni 'FIXED' psPlus
DVMagicMarker ~ 'REQUIRED'
              | 'CURRENT'
              | 'CONREF'
              | 'IMPLIED'
NotationDeclaration ~ mdo 'NOTATION' psPlus NotationName psPlus NotationIdentifier psStar mdc bless => DECL assoc => group
NotationIdentifier ~ ExternalIdentifier
AssociatedNotationName ~ rni 'NOTATION' psPlus NotationName
                       | rni 'NOTATION' psPlus NameGroup
DataAttributeSpecification ~ psPlus dso AttributeSpecificationPlus sStar dsc
ShortReferenceMappingDeclaration ~ mdo 'SHORTREF' psPlus MapName PLNmPlus psStar mdc bless => DECL assoc => group
PLNmPlus ~ PLNm+
PLNm ~ psPlus ParameterLiteral psPlus Name
MapName ~ Name
ShortReferenceUseDeclaration ~ mdo 'USEMAP' psPlus MapSpecification AETGuts psStar mdc bless => DECL assoc => group
AETGuts ~ psPlus AssociatedElementType
        | Nothing
MapSpecification ~ MapName
                 | rni 'EMPTY'
LTD ~ mdo 'LINKTYPE' psPlus LinkTypeName psPlus LinkSpecification ExtIDGuts WrappedLTDSubset psStar mdc bless => LTD assoc => group
LinkSpecification ~ SimpleLinkSpecification
                  | ImplicitLinkSpecification
                  | ExplicitLinkSpecification
ExtIDGuts ~ psPlus ExternalIdentifier
          | Nothing
WrappedLTDSubset ~ psPlus dso LTDSubset dsc
                 | Nothing
LinkTypeName ~ Name
SimpleLinkSpecification ~ rni 'SIMPLE' psPlus rni 'IMPLIED'
ImplicitLinkSpecification ~ SourceDocumentTypeName psPlus rni 'IMPLIED'
ExplicitLinkSpecification ~ SourceDocumentTypeName psPlus ResultDocumentTypeName
SourceDocumentTypeName ~ DocumentTypeName
ResultDocumentTypeName ~ DocumentTypeName
LTDSubset ~ LinkyThingStar OptionalIDLinkSetDeclaration LinkyThingStar
OptionalIDLinkSetDeclaration ~ IDLinkSetDeclaration
                             | Nothing
LinkyThingStar ~ LinkyThing*
LinkyThing ~ LinkAttributeSet
           | LinkSetDeclaration
LinkAttributeSet ~ AttributeDefinitionListDeclaration
                 | EntitySet
LinkSetDeclaration ~ mdo 'LINK' psPlus LinkSetName psPlus LinkRule psStar mdc bless => DECL assoc => group
LinkRule ~ SourceElementSpecification
         | ExplicitLinkRule
LinkSetName ~ Name
            | rni 'INITIAL'
SourceElementSpecification ~ AssociatedElementType UselinkGuts PostlinkGuts LinkAttributeSpecification
UseLinkGuts ~ psPlus rni 'USELINK' psPlus LSNGuts
            | Nothing
LSNGuts ~ LinkSetName
        | rni 'EMPTY'
PostlinkGuts ~ psPlus rni 'POSTLINK' psPlus LinkSetSpecification
             | Nothing
LinkAttributeSpecification ~ sPlus dso AttributeSpecificationPlus sPlus dsc
                           | Nothing
ExplicitLinkRule ~ SourceElementSpecification psPlus ResultElementSpecification
                 | SourceElementSpecification psPlus rni 'IMPLIED'
                 | rni 'IMPLIED' psPlus ResultElementSpecification
ResultElementSpecification ~ GenericIdentifier
                           | GenericIdentifier ResultAttributeSpecification
ResultAttributeSpecification ~ sPlus dso AttributeSpecificationPlus dsc
AttributeSpecificationPlus ~ AttributeSpecification+
IDLinkSetDeclaration ~ mdo 'USELINK' psPlus LinkSetSpecification psPlus LinkTypeName psStar mdc bless => DECL assoc => group
LinkSetSpecification ~ LinkSetName
                     | rni 'EMPTY'
                     | rni 'RESTORE'
SGMLDeclaration ~ mdo 'SGML' psPlus MinimumLiteral
                             psPlus DocumentCharacterSet
                             psPlus CapacitySet
                             psPlus ConcreteSyntaxScope
                             psPlus ConcreteSyntax
                             psPlus FeatureUse
                             psPlus ApplicationSpecificInformation
                             psStar
                  mdc bless => DECL assoc => group
DocumentCharacterSet ~ 'CHARSET' CharacterSetDescriptionList
CharacterSetDescriptionList ~ CharacterSetDescription+
CharacterSetDescription ~ psPlus BaseCharacterSet psPlus DescribedCharacterSetPortion
BaseCharacterSet ~ 'BASESET' psPlus PublicIdentifier
DescribedCharacterSetPortion ~ 'DESCSET' CDGutsList
CDGutsList ~ CDGuts+
CDGuts ~ psPlus CharacterDescription
CharacterDescription ~ DescribedSetCharacterNumber psPlus NumberOfCharacters psPlus CharDescChoice
CharDescChoice ~ BaseSetCharacterNumber
               | MinimumLiteral
               | 'UNUSED'
DescribedSetCharacterNumber ~ CharacterNumber
BaseSetCharacterNumber ~ CharacterNumber
NumberOfCharacters ~ Number
CapacitySet ~ 'CAPACITY' psPlus CapacityGuts
CapacityGuts ~ PublicCapacity
             | SGMLRefCapacity
PublicCapacity ~ 'PUBLIC' psPlus PublicIdentifier
SGMLRefCapacity ~ 'SGMLREF' SGMLRefCapacityGutsPlus
SGMLRefCapacityListGuts ~ psPlus Name psPlus Number
ConcreteSyntaxScope ~ 'SCOPE' psPlus 'DOCUMENT'
                    | 'SCOPE' psPlus 'INSTANCE'
ConcreteSyntax ~ 'SYNTAX' psPlus ConcSynType
ConcSynType ~ PublicConcreteSyntax
            | PrivateConcreteSyntax
PrivateConcreteSyntax ~ ShunnedCharacterNumberIdentification
                        psPlus SyntaxReferenceCharacterSet
                        psPlus FunctionCharacterIdentification
                        psPlus NamingRules
                        psPlus DelimiterSet
                        psPlus ReservedNameUse
                        psPlus QuantitySet
PublicConcreteSyntax ~ 'PUBLIC' psPlus PublicIdentifier
                     | 'PUBLIC' psPlus PublicIdentifier PublicSwitches
PublicSwitches ~ 'SWITCHES' PublicSwitchPlus
PublicSwitchPlus ~ PublicSwitch+
PublicSwitch ~ psPlus CharacterNumber psPlus CharacterNumber
ShunnedCharacterNumberIdentification ~ 'SHUNCHAR' psPlus 'NONE'
                                     | 'SHUNCHAR' psPlus 'CONTROLS' SCNList
SCNList ~ SCN+
SCN ~ psPlus CharacterNumber
SyntaxReferenceCharacterSet ~ CharacterSetDescription
FunctionCharacterIdentification ~ 'FUNCTION' psPlus 'RE' psPlus CharacterNumber
                                             psPlus 'RS' psPlus CharacterNumber
                                             psPlus 'SPACE' psPlus CharacterNumber
                                             AddedFunctionCharacterStar
AddedFunctionCharacterStar ~ AddedFunctionCharacter
AddedFunctionCharacter ~ psPlus AddedFunction psPlus FunctionClass psPlus CharacterNumber
AddedFunction ~ Name
FunctionClass ~ 'FUNCHAR'
              | 'MSICHAR'
              | 'MSOCHAR'
              | 'MSSCHAR'
              | 'SEPCHAR'
NamingRules ~ 'NAMING' psPlus 'LCNMSTART' psPlus ParameterLiteral
                       psPlus 'UCNMSTART' psPlus ParameterLiteral
                       psPlus 'LCNMCHAR' psPlus ParameterLiteral
                       psPlus 'UCNMCHAR' psPlus ParameterLiteral
                       psPlus 'NAMECASE' psPlus 'GENERAL' psPlus Boolean
                       psPlus 'ENTITY' psPlus Boolean
Boolean ~ 'YES' @literal => 1 @quoted => 0
        | 'NO' @literal => 1 @quoted => 0
CountedBoolean ~ 'YES' psPlus Number @literal => 1 @quoted => 0
               | 'NO' @literal => 1 @quoted => 0
ASN1Boolean ~ 'YES' psPlus 'ASN1' @literal => 1 @quoted => 0
            | 'YES' @literal => 1 @quoted => 0
            | 'NO' @literal => 1 @quoted => 0
DelimiterSet ~ 'DELIM' psPlus GeneralDelimiters psPlus ShortReferenceDelimiters
GeneralDelimiters ~ 'GENERAL' psPlus 'SGMLREF' SGMLDelimPlus
SGMLDelimPlus ~ SGMLDelim+
SGMLDelim ~ psPlus Name psPlus ParameterLiteral
ShortReferenceDelimiters ~ 'SHORTREF' psPlus 'SGMLREF' PLList
                         | 'SHORTREF' psPlus 'NONE' PLList
PLList ~ PL+
PL ~ psPlus ParameterLiteral
ReservedNameUse ~ 'NAMES' psPlus 'SGMLREF' NamePairPlus
NamePairPlus ~ NamePair+
NamePair ~ psPlus Name psPlus Name
QuantitySet ~ 'QUANTITY' psPlus 'SGMLREF' NameQuantityPlus
NameQuantityPlus ~ NameQuantity+
NameQuantity ~ psPlus Name psPlus Number
FeatureUse ~ 'FEATURES' psPlus MarkupMinimizationFeatures
                        psPlus LinkTypeFeatures
                        psPlus OtherFeatures
MarkupMinimizationFeatures ~ 'MINIMIZE' psPlus 'DATATAG' psPlus Boolean
                                        psPlus 'OMITTAG' psPlus Boolean
                                        psPlus 'RANK' psPlus Boolean
                                        psPlus 'SHORTTAG' psPlus Boolean
LinkTypeFeatures ~ 'LINK' psPlus 'SIMPLE' psPlus CountedBoolean
                          psPlus 'IMPLICIT' psPlus Boolean
                          psPlus 'EXPLICIT' psPlus CountedBoolean
OtherFeatures ~ 'OTHER' psPlus 'CONCUR' psPlus CountedBoolean
                        psPlus 'SUBDOC' psPlus CountedBoolean
                        psPlus 'FORMAL' psPlus Boolean
ApplicationSpecificInformation ~ 'APPINFO' psPlus 'NONE'
                               | 'APPINFO' psPlus MinimumLiteral
SystemDeclaration ~ mdo 'SYSTEM' psPlus MinimumLiteral
                                 psPlus DocumentCharacterSet
                                 psPlus CapacitySet
                                 psPlus FeatureUse
                                 psPlus ConcreteSyntaxScope
                                 psPlus ConcreteSyntaxesSupportedPlus
                                 psPlus ValidationServices
                                 psPlus SDIFSupport
                                 psStar
                    mdc bless => DECL assoc => group
ConcreteSyntaxesSupportedPlus ~ ConcreteSyntaxesSupported+
ConcreteSyntaxesSupported ~ psPlus ConcreteSyntax
                          | psPlus ConcreteSyntax psPlus ConcreteSyntaxChanges
ConcreteSyntaxChanges ~ 'CHANGES' psPlus 'SWITCHES'
                      | 'CHANGES' psPlus 'DELIMLEN' psPlus Number
                                  psPlus 'SEQUENCE' psPlus Boolean
                                  psPlus 'SRCNT' psPlus Number
                                  psPlus 'SRLEN' psPlus Number
ValidationServices ~ 'VALIDATE' psPlus 'GENERAL' psPlus Boolean
                                psPlus 'MODEL' psPlus Boolean
                                psPlus 'EXCLUDE' psPlus Boolean
                                psPlus 'CAPACITY' psPlus Boolean
                                psPlus 'NONSGML' psPlus Boolean
                                psPlus 'SGML' psPlus Boolean
                                psPlus 'FORMAL' psPlus Boolean
SDIFSupport ~ 'SDIF' psPlus 'PACK' psPlus ASN1Boolean
                     psPlus 'UNPACK' psPlus ASN1Boolean
RE ~ [\x{D}] bless => WHITESPACE
RS ~ [\x{A}] bless => WHITESPACE
SPACE ~ [\x{20}] bless => WHITESPACE
SEPCHAR ~ [\x{9}] bless => WHITESPACE
LCLetter ~ [a-z]
UCLetter ~ [A-Z]
Digit ~ [0-9]
lit ~ ["]
lita ~ [']
Squo ~ [']
stago ~ '<'
tagc ~ '>'
neto ~ '/'
netc ~ '/'
etago ~ '</'
pio ~ '<?'
pic ~ '?>'
dtgo ~ '['
dtgc ~ ']'
mdo ~ '<!'
mdc ~ '>'
dso ~ '['
msc ~ ']]'
shortref ~ '&#TAB;'
         | '&#RE;'
         | '&#RS;'
         | '&#RS;B'
         | '&#RS;&#RE;'
         | '&#RS;B&#RE;'
         | 'B&#RE;'
         | '&#SPACE;'
         | 'BB'
         | '"'
         | '#'
         | '%'
         | Squo
         | '('
         | ')'
         | '*'
         | '+'
         | ','
         | '-'
         | '--'
         | ':'
         | ';'
         | '='
         | '@'
         | '['
         | ']'
         | '^'
         | '_'
         | '{'
         | '|'
         | '}'
         | '~'
vi ~ '='
plus ~ '+'
minus ~ '-'
slashslash ~ '//'
LCNMCHAR ~ '-'
         | '.'
ero ~ '&'
pero ~ '%'
refc ~ ';'
cro ~ '&#'
grpo ~ '('
grpc ~ ')'
Special ~ '('
        | ')'
        | '+'
        | ','
        | '-'
        | '.'
        | '/'
        | ':'
        | '='
        | '?'
        | Squo
com ~ '--'
rni ~ '#'
and ~ '&'
or ~ '|'
seq ~ ','
opt ~ '?'
rep ~ '*'
Ee ~ bless => EE
Nothing ~
