<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scopeName</key>
    <string>text.xml.tmlanguage</string>
    <key>fileTypes</key>
    <array>
        <string>tmLanguage</string>
    </array>
    <key>name</key>
    <string>tmLanguage</string>
    <key>foldingStartMarker</key>
    <string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
    <key>foldingStopMarker</key>
    <string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#plist</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.xml</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>plist</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#plistDecl</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#outerDict</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#array</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>text.xml</string>
                </dict>
            </array>
        </dict>
        <key>plistDecl</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(plist)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string> (?:([-_a-zA-Z0-9]+)((:)))?([a-zA-Z-]+)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.other.attribute-name.namespace.xml</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.other.attribute-name.xml</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.namespace.xml</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.other.attribute-name.localname.xml</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#doublequotedString</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#singlequotedString</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>text.xml</string>
                </dict>
            </array>
        </dict>
        <key>doublequotedString</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.xml.tmlanguage</string>
        </dict>
        <key>singlequotedString</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.xml.tmlanguage</string>
        </dict>
        <key>outerDict</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(dict)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(dict)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#outerDecls</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#repoDict</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#kvPair</string>
                </dict>
            </array>
        </dict>
        <key>outerDecls</key>
        <dict>
            <key>match</key>
            <string>(&lt;)(key)(&gt;)(scopeName|fileTypes|name|patterns|repository)(&lt;/)(key)(&gt;)</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.variable.xml.tmlanguage</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
        </dict>
        <key>string</key>
        <dict>
            <key>match</key>
            <string>(&lt;)(string)(&gt;)(.+?)(&lt;/)(string)(&gt;)</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>string.quoted.single.xml.tmlanguage</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
        </dict>
        <key>definitionPair</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(key)(&gt;)(match|begin|end|foldingStartMarker|foldingStopMarker)(&lt;/)(key)(&gt;)</string>
            <key>end</key>
            <string>(&lt;)(string)(&gt;)(.+)(&lt;/)(string)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.key.xml.tmlanguage</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>string.regexp.compile.xml.tmlanguage</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
        </dict>
        <key>repoDict</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(dict)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(dict)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#repoKvPair</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#dict</string>
                </dict>
            </array>
        </dict>
        <key>dict</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(dict)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(dict)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#kvPair</string>
                </dict>
            </array>
        </dict>
        <key>kvPair</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#definitionPair</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#dict</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#array</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#key</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>text.xml</string>
                </dict>
           </array>
        </dict>
        <key>repoKvPair</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#dict</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#repoKey</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>text.xml</string>
                </dict>
           </array>
        </dict>
        <key>array</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(array)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(array)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#arrayElement</string>
                </dict>
            </array>
        </dict>
        <key>key</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(key)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(key)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>constant.other.key.xml.tmlanguage</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#arrayElement</string>
                </dict>
            </array>
        </dict>
        <key>repoKey</key>
        <dict>
            <key>begin</key>
            <string>(&lt;)(key)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(key)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.xml.tmlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.tmlanguage</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>punctuation.definition.variable.xml.tmlanguage</string>
        </dict>
        <key>arrayElement</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#array</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#dict</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>text.xml</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>uuid</key>
    <string>0BADC0CE-6D1C-11D9-8CC2-010D93589AF6</string>
</dict>
</plist>
