Nothing ~
RE ~ [\s]
RS ~ [\s]
SPACE ~ [\s]
SEPCHAR ~ [\s]
LCLetter ~ [a-z]
UCLetter ~ [A-Z]
DIGIT ~ [0-9]
lit ~ ["]
lita ~ [']
stago ~ '<'
etago ~ '</'
tagc ~ '>'
neto ~ '/'
netc ~ '/'
pio ~ '<?'
pic ~ '?>'
dtgo ~ '['
dtgc ~ ']'
mdo ~ '<!'
mdc ~ '>'
dso ~ '['
dsc ~ ']'
msc ~ ']]'
ero ~ '&'
pero ~ '%'
refc ~ ';'
cro ~ '&#'
grpo ~ '('
grpc ~ ')'
vi ~ '='
plus ~ '+'
minus ~ '-'
LCNMSTRT ~ [a-z]
UCNMSTRT ~ [A-Z]
LCNMCHAR ~ '-'
         | '.'
         | [a-z]
UCNMCHAR ~ [A-Z]
MSOCHAR ~ [\p{Separator}]
MSICHAR ~ [\p{Separator}]
MSSCHAR ~ [\p{Separator}]
FUNCHAR ~ [\p{Separator}]
com ~ '--'
rni ~ '#'
and ~ '&'
or ~ '|'
seq ~ ','
opt ~ '?'
rep ~ '*'
NONSGML ~ [^[:ascii:]]
DATACHAR ~ [\p{MarpaX::SGML::IsDataChar}]
DELMCHAR ~ [\p{Separator}]
NameCharacter ~ NMCHAR
NMCHARS ~ NMCHAR*
NMCHAR ~ NMSTRT
       | DIGIT
       | LCNMCHAR
       | UCNMCHAR
NMSTRT ~ LCLetter
       | UCLetter
       | LCNMSTRT
       | UCNMSTRT
FunctionCharacter ~ RE
                  | RS
                  | SPACE
                  | SEPCHAR
                  | MSOCHAR
                  | MSICHAR
                  | MSSCHAR
                  | FUNCHAR
Name ~ NAME
NAME ~ NMSTRT NMCHARS
Number ~ DIGIT+
Digit ~ DIGIT
NUMBER ~ DIGIT+
