CapacitySet ::= 'CAPACITY' ps CapacityGuts
CapacityGuts ::= PublicCapacity
               | SGMLRefCapacity
PublicCapacity ::= 'PUBLIC' ps PublicIdentifier
SGMLRefCapacity ::= 'SGMLREF' SGMLRefCapacityListGuts
SGMLRefCapacityListGuts ::= SGMLRefCapacityGuts SGMLRefCapacityListGuts
                          | SGMLRefCapacityGuts
SGMLRefCapacityGuts ::= ps Name ps Number
FeatureUse ::= 'FEATURES' ps MarkupMinimizationFeatures
                          ps LinkTypeFeatures
                          ps OtherFeatures
MarkupMinimizationFeatures ::= 'MINIMIZE' ps 'DATATAG' ps Boolean
                                          ps 'OMITTAG' ps Boolean
                                          ps 'RANK' ps Boolean
                                          ps 'SHORTTAG' ps Boolean
LinkTypeFeatures ::= 'LINK' ps 'SIMPLE' ps CountedBoolean
                            ps 'IMPLICIT' ps Boolean
                            ps 'EXPLICIT' ps CountedBoolean
OtherFeatures ::= 'OTHER' ps 'CONCUR' ps CountedBoolean
                          ps 'SUBDOC' ps CountedBoolean
                          ps 'FORMAL' ps Boolean
Squo ~ [']
Special ~ '('
        | ')'
        | '+'
        | ','
        | '-'
        | '.'
        | '/'
        | ':'
        | '='
        | '?'
        | Squo
shortref ~ '&#TAB;'
         | '&#RE;'
         | '&#RS;'
         | '&#RS;B'
         | '&#RS;&#RE;'
         | '&#RS;B&#RE;'
         | 'B&#RE;'
         | '&#SPACE;'
         | 'BB'
         | '"'
         | '#'
         | '%'
         | Squo
         | '('
         | ')'
         | '*'
         | '+'
         | ','
         | '-'
         | '--'
         | ':'
         | ';'
         | '='
         | '@'
         | '['
         | ']'
         | '^'
         | '_'
         | '{'
         | '|'
         | '}'
         | '~'
slashslash ~ <double slash>
<double slash> ~ '//'
CharacterSetDescription ::= ps BaseCharacterSet ps DescribedCharacterSetPortion
BaseCharacterSet ::= 'BASESET' ps PublicIdentifier
DescribedCharacterSetPortion ::= 'DESCSET' ps CharacterDescriptions
                               | Nil
CharacterDescriptions ::= CharacterDescription ps CharacterDescriptions
                        | CharacterDescription
CharacterDescription ::= DescribedSetCharacterNumber ps NumberOfCharacters ps CharDescChoice
CharDescChoice ::= BaseSetCharacterNumber
                 | MinimumLiteral
                 | 'UNUSED'
DescribedSetCharacterNumber ::= CharacterNumber
BaseSetCharacterNumber ::= CharacterNumber
NumberOfCharacters ::= Number
